package com.example.anime.model

import com.example.anime.R

data class Anime(
    val title: String,
    val type: String,
    val image: Int,
    val rating: String,
    val synopsis: String
)

val dummyAnime = listOf(
    Anime("Boruto: Naruto Next Generations", "TV, Spring 2017", R.drawable.boruto, "6.03", "Following the successful end of the Fourth Shinobi World War, Konohagakure has been enjoying a period of peace, prosperity, and extraordinary technological advancement. This is all due to the efforts of the Allied Shinobi Forces and the village\\'s Seventh Hokage, Naruto Uzumaki. Now resembling a modern metropolis, Konohagakure has changed, particularly the life of a shinobi. Under the watchful eye of Naruto and his old comrades, a new generation of shinobi has stepped up to learn the ways of the ninja.\\n Boruto Uzumaki is often the center of attention as the son of the Seventh Hokage. Despite having inherited Naruto\\'s boisterous and stubborn demeanor, Boruto is considered a prodigy and is able to unleash his potential with the help of supportive friends and family. Unfortunately, this has only worsened his arrogance and his desire to surpass Naruto which, along with his father\\'s busy lifestyle, has strained their relationship. However, a sinister force brewing within the village may threaten Boruto\\'s carefree life."),
    Anime("Ore dake Level Up na Ken", "TV, Winter 2024", R.drawable.solev, "8.42", "Humanity was caught at a precipice a decade ago when the first gates—portals linked with other dimensions that harbor monsters immune to conventional weaponry—emerged around the world. Alongside the appearance of the gates, various humans were transformed into hunters and bestowed superhuman abilities. Responsible for entering the gates and clearing the dungeons within, many hunters chose to form guilds to secure their livelihoods.\\n Sung Jin-Woo is an E-rank hunter dubbed as the weakest hunter of all mankind. While exploring a supposedly safe dungeon, he and his party encounter an unusual tunnel leading to a deeper area. Enticed by the prospect of treasure, the group presses forward, only to be confronted with horrors beyond their imagination. Miraculously, Jin-Woo survives the incident and soon finds that he now has access to an interface visible only to him. This mysterious system promises him the power he has long dreamed of—but everything comes at a price."),
    Anime("Yubisaki to Renren", "TV, Winter 2024", R.drawable.yubisaki, "8.30", "For hearing-impaired university student Yuki Itose, silence has been a natural part of life since birth. Her world is small and isolated; she commutes to campus, interacts with her best friend Rin Fujishiro, and communicates through writing and text messages—a lifestyle that offers little to no change. One day, during her commute, Yuki meets fellow student Itsuomi Nagi, a multilingual travel enthusiast and friend of Rin. When Itsuomi learns of Yuki\\'s condition, he takes it in stride, moving Yuki\\'s heart. From this one simple gesture, Yuki and Itsuomi\\'s lives start changing day by day as they let each other into their own worlds."),
    Anime("Black Clover", "TV, Fall 2017", R.drawable.clover, "8.14", "Asta and Yuno were abandoned at the same church on the same day. Raised together as children, they came to know of the \\\"Wizard King\\\"—a title given to the strongest mage in the kingdom—and promised that they would compete against each other for the position of the next Wizard King. However, as they grew up, the stark difference between them became evident. While Yuno is able to wield magic with amazing power and control, Asta cannot use magic at all and desperately tries to awaken his powers by training physically.\\n When they reach the age of 15, Yuno is bestowed a spectacular Grimoire with a four-leaf clover, while Asta receives nothing. However, soon after, Yuno is attacked by a person named Lebuty, whose main purpose is to obtain Yuno\\'s Grimoire. Asta tries to fight Lebuty, but he is outmatched. Though without hope and on the brink of defeat, he finds the strength to continue when he hears Yuno\\'s voice. Unleashing his inner emotions in a rage, Asta receives a five-leaf clover Grimoire, a \\\"Black Clover\\\" giving him enough power to defeat Lebuty. A few days later, the two friends head out into the world, both seeking the same goal—to become the Wizard King!"),
    Anime("Darwin\\'s Game", "TV, Winter 2020", R.drawable.darwin, "7.22", "High school student Kaname Sudou receives an invitation from a classmate to play Darwin\\'s Game, a mobile game he has never heard of. However, as soon as he opens the application, a green snake suddenly pops out from his phone screen and bites his neck, leaving him unconscious. Waking up in the infirmary without any signs of a snake bite, he is told by the school to take the rest of the day off. Although he is puzzled by what has happened, he dismisses the surreal experience as a hallucination and boards the train home.\\n Unfortunately, his curiosity gets the better of him and he uses the application once again. As the application appears to be just like any other battle game, Kaname breathes out a sigh of relief and decides to start his first match. However, the pleasant surprise is short-lived, as his in-game opponent unexpectedly appears right in front of him and attempts to hunt him down with a knife.\\n As he desperately runs for his life, Kaname puts two and two together and realizes that Darwin\\'s Game is not an ordinary game, but rather, it\\'s a brutal fight for survival."),
    Anime("Dr. Stone", "TV, Summer 2019", R.drawable.senku, "8.28", "After five years of harboring unspoken feelings, high-schooler Taiju Ooki is finally ready to confess his love to Yuzuriha Ogawa. Just when Taiju begins his confession however, a blinding green light strikes the Earth and petrifies mankind around the world—turning every single human into stone.\\n Several millennia later, Taiju awakens to find the modern world completely nonexistent, as nature has flourished in the years humanity stood still. Among a stone world of statues, Taiju encounters one other living human: his science-loving friend Senkuu, who has been active for a few months. Taiju learns that Senkuu has developed a grand scheme—to launch the complete revival of civilization with science. Taiju\\'s brawn and Senkuu\\'s brains combine to forge a formidable partnership, and they soon uncover a method to revive those petrified.\\n However, Senkuu\\'s master plan is threatened when his ideologies are challenged by those who awaken. All the while, the reason for mankind\\'s petrification remains unknown."),
    Anime("Edens Zero", "TV, Spring 2021", R.drawable.edens, "7.29", "All his life, Shiki has been surrounded by machines. At Granbell Kingdom, a long-abandoned amusement park, he is the only one of his kind around. That is, until Rebecca Bluegarden and her feline companion Happy arrive, unaware that they are Granbell\\'s first visitors in one hundred years. Their goal is to make fun videos for their B-Cube channel, but what they find instead is a friend in the socially awkward Shiki.\\n When Granbell becomes too dangerous for the three of them, they set off on an adventure through the Sakura Cosmos. They hope to make more interesting videos and even find the elusive goddess Mother, while Shiki wants to make more friends, spurred on by the words of his late grandfather. Of course, the journey will not be easy, as no one has seen Mother before, but Shiki is determined to reach his goal and explore the boundless reaches of space together with his new friends."),
    Anime("Haikyuu!!", "TV, Spring 2014", R.drawable.haikyuu, "8.44", "Ever since having witnessed the \\\"Little Giant\\\" and his astonishing skills on the volleyball court, Shouyou Hinata has been bewitched by the dynamic nature of the sport. Even though his attempt to make his debut as a volleyball regular during a middle school tournament went up in flames, he longs to prove that his less-than-impressive height ceases to be a hindrance in the face of his sheer will and perseverance.\\n When Hinata enrolls in Karasuno High School, the Little Giant\\'s alma mater, he believes that he is one step closer to his goal of becoming a professional volleyball player. Although the school only retains a shadow of its former glory, Hinata\\'s conviction isn\\'t shaken until he learns that Tobio Kageyama—the prodigy who humiliated Hinata\\'s middle school volleyball team in a crushing defeat—is now his teammate.\\n To fulfill his desire of leaving a mark on the realm of volleyball—so often regarded as the domain of the tall and the strong—Hinata must smooth out his differences with Kageyama. Only when Hinata learns what it takes to be a part of a team will he be able to join the race to the top in earnest."),
    Anime("Josee to Tora to Sakana-tachi", "Movie, 2020", R.drawable.jose, "8.39", "Equipped with his passion for diving and admiration for marine biology, university student Tsuneo Suzukawa tries his best to juggle several part-time jobs to earn enough money to study abroad. But one night, in a fateful accident, he meets a girl in a wheelchair, driving his current path into a detour.\\n The girl, Kumiko—who prefers to be called \\\"Josee\\\"—initially comes off as rude. Tsuneo, however, is then convinced by Josee\\'s grandmother to take on the paid job to be Josee\\'s caretaker. Despite being annoyed with her bossy demeanor, Tsuneo sees the opportunity to save more funds to support his academic dream. Nonetheless, after putting up with Josee\\'s behavior for some time, Tsuneo tries to quit, only to discover Josee\\'s dreams of traversing the outside world—to experience a life free from her crippling condition.\\n Changing his mind, Tsuneo decides to accompany Josee in exploring the wonders that the world has to offer. Through their time together, the two begin to realize that the traits that bind them may be vital toward fulfilling their respective aspirations."),
    Anime("Kimetsu no Yaiba", "TV, Spring 2019", R.drawable.kimetsu,"8.48", "Ever since the death of his father, the burden of supporting the family has fallen upon Tanjirou Kamado\\'s shoulders. Though living impoverished on a remote mountain, the Kamado family are able to enjoy a relatively peaceful and happy life. One day, Tanjirou decides to go down to the local village to make a little money selling charcoal. On his way back, night falls, forcing Tanjirou to take shelter in the house of a strange man, who warns him of the existence of flesh-eating demons that lurk in the woods at night.\\n When he finally arrives back home the next day, he is met with a horrifying sight—his whole family has been slaughtered. Worse still, the sole survivor is his sister Nezuko, who has been turned into a bloodthirsty demon. Consumed by rage and hatred, Tanjirou swears to avenge his family and stay by his only remaining sibling. Alongside the mysterious group calling themselves the Demon Slayer Corps, Tanjirou will do whatever it takes to slay the demons and protect the remnants of his beloved sister\\'s humanity.")
)